package cl.aba.model.web.common;
// Generated 27-04-2017 11:06:14 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AdjudicadoEstados generated by hbm2java
 */
public class AdjudicadoEstados  implements java.io.Serializable {


     private int adjudicadoEstadoId;
     private AdjudicadoEstados adjudicadoEstados;
     private String adjudicadoEstadoTx;
     private Set adjudicadoEstadoses = new HashSet(0);
     private Set rbdEstadoses = new HashSet(0);

    public AdjudicadoEstados() {
    }

	
    public AdjudicadoEstados(int adjudicadoEstadoId) {
        this.adjudicadoEstadoId = adjudicadoEstadoId;
    }
    public AdjudicadoEstados(int adjudicadoEstadoId, AdjudicadoEstados adjudicadoEstados, String adjudicadoEstadoTx, Set adjudicadoEstadoses, Set rbdEstadoses) {
       this.adjudicadoEstadoId = adjudicadoEstadoId;
       this.adjudicadoEstados = adjudicadoEstados;
       this.adjudicadoEstadoTx = adjudicadoEstadoTx;
       this.adjudicadoEstadoses = adjudicadoEstadoses;
       this.rbdEstadoses = rbdEstadoses;
    }
   
    public int getAdjudicadoEstadoId() {
        return this.adjudicadoEstadoId;
    }
    
    public void setAdjudicadoEstadoId(int adjudicadoEstadoId) {
        this.adjudicadoEstadoId = adjudicadoEstadoId;
    }
    public AdjudicadoEstados getAdjudicadoEstados() {
        return this.adjudicadoEstados;
    }
    
    public void setAdjudicadoEstados(AdjudicadoEstados adjudicadoEstados) {
        this.adjudicadoEstados = adjudicadoEstados;
    }
    public String getAdjudicadoEstadoTx() {
        return this.adjudicadoEstadoTx;
    }
    
    public void setAdjudicadoEstadoTx(String adjudicadoEstadoTx) {
        this.adjudicadoEstadoTx = adjudicadoEstadoTx;
    }
    public Set getAdjudicadoEstadoses() {
        return this.adjudicadoEstadoses;
    }
    
    public void setAdjudicadoEstadoses(Set adjudicadoEstadoses) {
        this.adjudicadoEstadoses = adjudicadoEstadoses;
    }
    public Set getRbdEstadoses() {
        return this.rbdEstadoses;
    }
    
    public void setRbdEstadoses(Set rbdEstadoses) {
        this.rbdEstadoses = rbdEstadoses;
    }




}


