package cl.aba.model.web.common;
// Generated 27-04-2017 11:06:14 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Adjudicaciones generated by hbm2java
 */
public class Adjudicaciones  implements java.io.Serializable {


     private int adjudicacionId;
     private RbdConcursos rbdConcursos;
     private TipoAdjudicaciones tipoAdjudicaciones;
     private Operadoras operadoras;
     private Tecnologias tecnologias;
     private BigDecimal precioAdjudicacionNu;
     private BigDecimal velocidadNacionalNu;
     private BigDecimal velocidadInternacionalNu;
     private Date fechaAdjudicacion;
     private Date fechaDesadjudicacion;

    public Adjudicaciones() {
    }

	
    public Adjudicaciones(int adjudicacionId, RbdConcursos rbdConcursos, Operadoras operadoras) {
        this.adjudicacionId = adjudicacionId;
        this.rbdConcursos = rbdConcursos;
        this.operadoras = operadoras;
    }
    public Adjudicaciones(int adjudicacionId, RbdConcursos rbdConcursos, TipoAdjudicaciones tipoAdjudicaciones, Operadoras operadoras, Tecnologias tecnologias, BigDecimal precioAdjudicacionNu, BigDecimal velocidadNacionalNu, BigDecimal velocidadInternacionalNu, Date fechaAdjudicacion, Date fechaDesadjudicacion) {
       this.adjudicacionId = adjudicacionId;
       this.rbdConcursos = rbdConcursos;
       this.tipoAdjudicaciones = tipoAdjudicaciones;
       this.operadoras = operadoras;
       this.tecnologias = tecnologias;
       this.precioAdjudicacionNu = precioAdjudicacionNu;
       this.velocidadNacionalNu = velocidadNacionalNu;
       this.velocidadInternacionalNu = velocidadInternacionalNu;
       this.fechaAdjudicacion = fechaAdjudicacion;
       this.fechaDesadjudicacion = fechaDesadjudicacion;
    }
   
    public int getAdjudicacionId() {
        return this.adjudicacionId;
    }
    
    public void setAdjudicacionId(int adjudicacionId) {
        this.adjudicacionId = adjudicacionId;
    }
    public RbdConcursos getRbdConcursos() {
        return this.rbdConcursos;
    }
    
    public void setRbdConcursos(RbdConcursos rbdConcursos) {
        this.rbdConcursos = rbdConcursos;
    }
    public TipoAdjudicaciones getTipoAdjudicaciones() {
        return this.tipoAdjudicaciones;
    }
    
    public void setTipoAdjudicaciones(TipoAdjudicaciones tipoAdjudicaciones) {
        this.tipoAdjudicaciones = tipoAdjudicaciones;
    }
    public Operadoras getOperadoras() {
        return this.operadoras;
    }
    
    public void setOperadoras(Operadoras operadoras) {
        this.operadoras = operadoras;
    }
    public Tecnologias getTecnologias() {
        return this.tecnologias;
    }
    
    public void setTecnologias(Tecnologias tecnologias) {
        this.tecnologias = tecnologias;
    }
    public BigDecimal getPrecioAdjudicacionNu() {
        return this.precioAdjudicacionNu;
    }
    
    public void setPrecioAdjudicacionNu(BigDecimal precioAdjudicacionNu) {
        this.precioAdjudicacionNu = precioAdjudicacionNu;
    }
    public BigDecimal getVelocidadNacionalNu() {
        return this.velocidadNacionalNu;
    }
    
    public void setVelocidadNacionalNu(BigDecimal velocidadNacionalNu) {
        this.velocidadNacionalNu = velocidadNacionalNu;
    }
    public BigDecimal getVelocidadInternacionalNu() {
        return this.velocidadInternacionalNu;
    }
    
    public void setVelocidadInternacionalNu(BigDecimal velocidadInternacionalNu) {
        this.velocidadInternacionalNu = velocidadInternacionalNu;
    }
    public Date getFechaAdjudicacion() {
        return this.fechaAdjudicacion;
    }
    
    public void setFechaAdjudicacion(Date fechaAdjudicacion) {
        this.fechaAdjudicacion = fechaAdjudicacion;
    }
    public Date getFechaDesadjudicacion() {
        return this.fechaDesadjudicacion;
    }
    
    public void setFechaDesadjudicacion(Date fechaDesadjudicacion) {
        this.fechaDesadjudicacion = fechaDesadjudicacion;
    }




}


