package cl.aba.model.web.common;
// Generated 27-04-2017 11:06:14 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Instalaciones generated by hbm2java
 */
public class Instalaciones  implements java.io.Serializable {


     private int instalacionId;
     private RbdConcursos rbdConcursos;
     private InstalacionExcepciones instalacionExcepciones;
     private TipoAdjudicaciones tipoAdjudicaciones;
     private Operadoras operadoras;
     private Tecnologias tecnologias;
     private BigDecimal precioInstalacionDecimal;
     private String urldocTx;
     private Date fechaAltaServicioFe;
     private String numeroFormularioAltaServicio;
     private BigDecimal velocidadNacionalNu;
     private BigDecimal velocidadInternacionalNu;
     private Date fechaDesintalacionFe;
     private Integer idci;

    public Instalaciones() {
    }

	
    public Instalaciones(int instalacionId, RbdConcursos rbdConcursos, Operadoras operadoras) {
        this.instalacionId = instalacionId;
        this.rbdConcursos = rbdConcursos;
        this.operadoras = operadoras;
    }
    public Instalaciones(int instalacionId, RbdConcursos rbdConcursos, InstalacionExcepciones instalacionExcepciones, TipoAdjudicaciones tipoAdjudicaciones, Operadoras operadoras, Tecnologias tecnologias, BigDecimal precioInstalacionDecimal, String urldocTx, Date fechaAltaServicioFe, String numeroFormularioAltaServicio, BigDecimal velocidadNacionalNu, BigDecimal velocidadInternacionalNu, Date fechaDesintalacionFe, Integer idci) {
       this.instalacionId = instalacionId;
       this.rbdConcursos = rbdConcursos;
       this.instalacionExcepciones = instalacionExcepciones;
       this.tipoAdjudicaciones = tipoAdjudicaciones;
       this.operadoras = operadoras;
       this.tecnologias = tecnologias;
       this.precioInstalacionDecimal = precioInstalacionDecimal;
       this.urldocTx = urldocTx;
       this.fechaAltaServicioFe = fechaAltaServicioFe;
       this.numeroFormularioAltaServicio = numeroFormularioAltaServicio;
       this.velocidadNacionalNu = velocidadNacionalNu;
       this.velocidadInternacionalNu = velocidadInternacionalNu;
       this.fechaDesintalacionFe = fechaDesintalacionFe;
       this.idci = idci;
    }
   
    public int getInstalacionId() {
        return this.instalacionId;
    }
    
    public void setInstalacionId(int instalacionId) {
        this.instalacionId = instalacionId;
    }
    public RbdConcursos getRbdConcursos() {
        return this.rbdConcursos;
    }
    
    public void setRbdConcursos(RbdConcursos rbdConcursos) {
        this.rbdConcursos = rbdConcursos;
    }
    public InstalacionExcepciones getInstalacionExcepciones() {
        return this.instalacionExcepciones;
    }
    
    public void setInstalacionExcepciones(InstalacionExcepciones instalacionExcepciones) {
        this.instalacionExcepciones = instalacionExcepciones;
    }
    public TipoAdjudicaciones getTipoAdjudicaciones() {
        return this.tipoAdjudicaciones;
    }
    
    public void setTipoAdjudicaciones(TipoAdjudicaciones tipoAdjudicaciones) {
        this.tipoAdjudicaciones = tipoAdjudicaciones;
    }
    public Operadoras getOperadoras() {
        return this.operadoras;
    }
    
    public void setOperadoras(Operadoras operadoras) {
        this.operadoras = operadoras;
    }
    public Tecnologias getTecnologias() {
        return this.tecnologias;
    }
    
    public void setTecnologias(Tecnologias tecnologias) {
        this.tecnologias = tecnologias;
    }
    public BigDecimal getPrecioInstalacionDecimal() {
        return this.precioInstalacionDecimal;
    }
    
    public void setPrecioInstalacionDecimal(BigDecimal precioInstalacionDecimal) {
        this.precioInstalacionDecimal = precioInstalacionDecimal;
    }
    public String getUrldocTx() {
        return this.urldocTx;
    }
    
    public void setUrldocTx(String urldocTx) {
        this.urldocTx = urldocTx;
    }
    public Date getFechaAltaServicioFe() {
        return this.fechaAltaServicioFe;
    }
    
    public void setFechaAltaServicioFe(Date fechaAltaServicioFe) {
        this.fechaAltaServicioFe = fechaAltaServicioFe;
    }
    public String getNumeroFormularioAltaServicio() {
        return this.numeroFormularioAltaServicio;
    }
    
    public void setNumeroFormularioAltaServicio(String numeroFormularioAltaServicio) {
        this.numeroFormularioAltaServicio = numeroFormularioAltaServicio;
    }
    public BigDecimal getVelocidadNacionalNu() {
        return this.velocidadNacionalNu;
    }
    
    public void setVelocidadNacionalNu(BigDecimal velocidadNacionalNu) {
        this.velocidadNacionalNu = velocidadNacionalNu;
    }
    public BigDecimal getVelocidadInternacionalNu() {
        return this.velocidadInternacionalNu;
    }
    
    public void setVelocidadInternacionalNu(BigDecimal velocidadInternacionalNu) {
        this.velocidadInternacionalNu = velocidadInternacionalNu;
    }
    public Date getFechaDesintalacionFe() {
        return this.fechaDesintalacionFe;
    }
    
    public void setFechaDesintalacionFe(Date fechaDesintalacionFe) {
        this.fechaDesintalacionFe = fechaDesintalacionFe;
    }
    public Integer getIdci() {
        return this.idci;
    }
    
    public void setIdci(Integer idci) {
        this.idci = idci;
    }




}


