package cl.aba.model.web.common;
// Generated 27-04-2017 11:06:14 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * ListaEspera generated by hbm2java
 */
public class ListaEspera  implements java.io.Serializable {


     private int listaEsperaId;
     private RbdConcursos rbdConcursos;
     private TipoAdjudicaciones tipoAdjudicaciones;
     private Operadoras operadoras;
     private Tecnologias tecnologias;
     private BigDecimal velocidadNacionalNu;
     private BigDecimal velocidadInternacionalNu;
     private BigDecimal precioNu;
     private Date plazoImplementacion;

    public ListaEspera() {
    }

	
    public ListaEspera(int listaEsperaId) {
        this.listaEsperaId = listaEsperaId;
    }
    public ListaEspera(int listaEsperaId, RbdConcursos rbdConcursos, TipoAdjudicaciones tipoAdjudicaciones, Operadoras operadoras, Tecnologias tecnologias, BigDecimal velocidadNacionalNu, BigDecimal velocidadInternacionalNu, BigDecimal precioNu, Date plazoImplementacion) {
       this.listaEsperaId = listaEsperaId;
       this.rbdConcursos = rbdConcursos;
       this.tipoAdjudicaciones = tipoAdjudicaciones;
       this.operadoras = operadoras;
       this.tecnologias = tecnologias;
       this.velocidadNacionalNu = velocidadNacionalNu;
       this.velocidadInternacionalNu = velocidadInternacionalNu;
       this.precioNu = precioNu;
       this.plazoImplementacion = plazoImplementacion;
    }
   
    public int getListaEsperaId() {
        return this.listaEsperaId;
    }
    
    public void setListaEsperaId(int listaEsperaId) {
        this.listaEsperaId = listaEsperaId;
    }
    public RbdConcursos getRbdConcursos() {
        return this.rbdConcursos;
    }
    
    public void setRbdConcursos(RbdConcursos rbdConcursos) {
        this.rbdConcursos = rbdConcursos;
    }
    public TipoAdjudicaciones getTipoAdjudicaciones() {
        return this.tipoAdjudicaciones;
    }
    
    public void setTipoAdjudicaciones(TipoAdjudicaciones tipoAdjudicaciones) {
        this.tipoAdjudicaciones = tipoAdjudicaciones;
    }
    public Operadoras getOperadoras() {
        return this.operadoras;
    }
    
    public void setOperadoras(Operadoras operadoras) {
        this.operadoras = operadoras;
    }
    public Tecnologias getTecnologias() {
        return this.tecnologias;
    }
    
    public void setTecnologias(Tecnologias tecnologias) {
        this.tecnologias = tecnologias;
    }
    public BigDecimal getVelocidadNacionalNu() {
        return this.velocidadNacionalNu;
    }
    
    public void setVelocidadNacionalNu(BigDecimal velocidadNacionalNu) {
        this.velocidadNacionalNu = velocidadNacionalNu;
    }
    public BigDecimal getVelocidadInternacionalNu() {
        return this.velocidadInternacionalNu;
    }
    
    public void setVelocidadInternacionalNu(BigDecimal velocidadInternacionalNu) {
        this.velocidadInternacionalNu = velocidadInternacionalNu;
    }
    public BigDecimal getPrecioNu() {
        return this.precioNu;
    }
    
    public void setPrecioNu(BigDecimal precioNu) {
        this.precioNu = precioNu;
    }
    public Date getPlazoImplementacion() {
        return this.plazoImplementacion;
    }
    
    public void setPlazoImplementacion(Date plazoImplementacion) {
        this.plazoImplementacion = plazoImplementacion;
    }




}


