package cl.aba.model.web.common;
// Generated 27-04-2017 11:06:14 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MineducEstados generated by hbm2java
 */
public class MineducEstados  implements java.io.Serializable {


     private int mineducEstadoId;
     private String mineducEstadoTx;
     private Set rbdEstadoses = new HashSet(0);

    public MineducEstados() {
    }

	
    public MineducEstados(int mineducEstadoId) {
        this.mineducEstadoId = mineducEstadoId;
    }
    public MineducEstados(int mineducEstadoId, String mineducEstadoTx, Set rbdEstadoses) {
       this.mineducEstadoId = mineducEstadoId;
       this.mineducEstadoTx = mineducEstadoTx;
       this.rbdEstadoses = rbdEstadoses;
    }
   
    public int getMineducEstadoId() {
        return this.mineducEstadoId;
    }
    
    public void setMineducEstadoId(int mineducEstadoId) {
        this.mineducEstadoId = mineducEstadoId;
    }
    public String getMineducEstadoTx() {
        return this.mineducEstadoTx;
    }
    
    public void setMineducEstadoTx(String mineducEstadoTx) {
        this.mineducEstadoTx = mineducEstadoTx;
    }
    public Set getRbdEstadoses() {
        return this.rbdEstadoses;
    }
    
    public void setRbdEstadoses(Set rbdEstadoses) {
        this.rbdEstadoses = rbdEstadoses;
    }




}


