package cl.aba.model.web.common;
// Generated 27-04-2017 11:06:14 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Operadoras generated by hbm2java
 */
public class Operadoras  implements java.io.Serializable {


     private int operadoraId;
     private String nombreSocialTx;
     private String aliasTx;
     private String observacionTx;
     private BigDecimal rut;
     private Set listaEsperas = new HashSet(0);
     private Set adjudicacioneses = new HashSet(0);
     private Set instalacioneses = new HashSet(0);

    public Operadoras() {
    }

	
    public Operadoras(int operadoraId) {
        this.operadoraId = operadoraId;
    }
    public Operadoras(int operadoraId, String nombreSocialTx, String aliasTx, String observacionTx, BigDecimal rut, Set listaEsperas, Set adjudicacioneses, Set instalacioneses) {
       this.operadoraId = operadoraId;
       this.nombreSocialTx = nombreSocialTx;
       this.aliasTx = aliasTx;
       this.observacionTx = observacionTx;
       this.rut = rut;
       this.listaEsperas = listaEsperas;
       this.adjudicacioneses = adjudicacioneses;
       this.instalacioneses = instalacioneses;
    }
   
    public int getOperadoraId() {
        return this.operadoraId;
    }
    
    public void setOperadoraId(int operadoraId) {
        this.operadoraId = operadoraId;
    }
    public String getNombreSocialTx() {
        return this.nombreSocialTx;
    }
    
    public void setNombreSocialTx(String nombreSocialTx) {
        this.nombreSocialTx = nombreSocialTx;
    }
    public String getAliasTx() {
        return this.aliasTx;
    }
    
    public void setAliasTx(String aliasTx) {
        this.aliasTx = aliasTx;
    }
    public String getObservacionTx() {
        return this.observacionTx;
    }
    
    public void setObservacionTx(String observacionTx) {
        this.observacionTx = observacionTx;
    }
    public BigDecimal getRut() {
        return this.rut;
    }
    
    public void setRut(BigDecimal rut) {
        this.rut = rut;
    }
    public Set getListaEsperas() {
        return this.listaEsperas;
    }
    
    public void setListaEsperas(Set listaEsperas) {
        this.listaEsperas = listaEsperas;
    }
    public Set getAdjudicacioneses() {
        return this.adjudicacioneses;
    }
    
    public void setAdjudicacioneses(Set adjudicacioneses) {
        this.adjudicacioneses = adjudicacioneses;
    }
    public Set getInstalacioneses() {
        return this.instalacioneses;
    }
    
    public void setInstalacioneses(Set instalacioneses) {
        this.instalacioneses = instalacioneses;
    }




}


