package cl.aba.model.web.common;
// Generated 27-04-2017 11:06:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RbdEstados generated by hbm2java
 */
public class RbdEstados  implements java.io.Serializable {


     private int rbdEstadoId;
     private ConectadoEstados conectadoEstados;
     private AdjudicadoEstados adjudicadoEstados;
     private RbdConcursos rbdConcursos;
     private MineducEstados mineducEstados;
     private Date fechaI;
     private Date fechaF;

    public RbdEstados() {
    }

	
    public RbdEstados(int rbdEstadoId, Date fechaI) {
        this.rbdEstadoId = rbdEstadoId;
        this.fechaI = fechaI;
    }
    public RbdEstados(int rbdEstadoId, ConectadoEstados conectadoEstados, AdjudicadoEstados adjudicadoEstados, RbdConcursos rbdConcursos, MineducEstados mineducEstados, Date fechaI, Date fechaF) {
       this.rbdEstadoId = rbdEstadoId;
       this.conectadoEstados = conectadoEstados;
       this.adjudicadoEstados = adjudicadoEstados;
       this.rbdConcursos = rbdConcursos;
       this.mineducEstados = mineducEstados;
       this.fechaI = fechaI;
       this.fechaF = fechaF;
    }
   
    public int getRbdEstadoId() {
        return this.rbdEstadoId;
    }
    
    public void setRbdEstadoId(int rbdEstadoId) {
        this.rbdEstadoId = rbdEstadoId;
    }
    public ConectadoEstados getConectadoEstados() {
        return this.conectadoEstados;
    }
    
    public void setConectadoEstados(ConectadoEstados conectadoEstados) {
        this.conectadoEstados = conectadoEstados;
    }
    public AdjudicadoEstados getAdjudicadoEstados() {
        return this.adjudicadoEstados;
    }
    
    public void setAdjudicadoEstados(AdjudicadoEstados adjudicadoEstados) {
        this.adjudicadoEstados = adjudicadoEstados;
    }
    public RbdConcursos getRbdConcursos() {
        return this.rbdConcursos;
    }
    
    public void setRbdConcursos(RbdConcursos rbdConcursos) {
        this.rbdConcursos = rbdConcursos;
    }
    public MineducEstados getMineducEstados() {
        return this.mineducEstados;
    }
    
    public void setMineducEstados(MineducEstados mineducEstados) {
        this.mineducEstados = mineducEstados;
    }
    public Date getFechaI() {
        return this.fechaI;
    }
    
    public void setFechaI(Date fechaI) {
        this.fechaI = fechaI;
    }
    public Date getFechaF() {
        return this.fechaF;
    }
    
    public void setFechaF(Date fechaF) {
        this.fechaF = fechaF;
    }




}


