package cl.aba.model.web.common;
// Generated 27-04-2017 11:06:14 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAdjudicaciones generated by hbm2java
 */
public class TipoAdjudicaciones  implements java.io.Serializable {


     private int tipoAdjId;
     private String tipoEsperaTx;
     private String descripcionTx;
     private Set instalacioneses = new HashSet(0);
     private Set adjudicacioneses = new HashSet(0);
     private Set listaEsperas = new HashSet(0);

    public TipoAdjudicaciones() {
    }

	
    public TipoAdjudicaciones(int tipoAdjId) {
        this.tipoAdjId = tipoAdjId;
    }
    public TipoAdjudicaciones(int tipoAdjId, String tipoEsperaTx, String descripcionTx, Set instalacioneses, Set adjudicacioneses, Set listaEsperas) {
       this.tipoAdjId = tipoAdjId;
       this.tipoEsperaTx = tipoEsperaTx;
       this.descripcionTx = descripcionTx;
       this.instalacioneses = instalacioneses;
       this.adjudicacioneses = adjudicacioneses;
       this.listaEsperas = listaEsperas;
    }
   
    public int getTipoAdjId() {
        return this.tipoAdjId;
    }
    
    public void setTipoAdjId(int tipoAdjId) {
        this.tipoAdjId = tipoAdjId;
    }
    public String getTipoEsperaTx() {
        return this.tipoEsperaTx;
    }
    
    public void setTipoEsperaTx(String tipoEsperaTx) {
        this.tipoEsperaTx = tipoEsperaTx;
    }
    public String getDescripcionTx() {
        return this.descripcionTx;
    }
    
    public void setDescripcionTx(String descripcionTx) {
        this.descripcionTx = descripcionTx;
    }
    public Set getInstalacioneses() {
        return this.instalacioneses;
    }
    
    public void setInstalacioneses(Set instalacioneses) {
        this.instalacioneses = instalacioneses;
    }
    public Set getAdjudicacioneses() {
        return this.adjudicacioneses;
    }
    
    public void setAdjudicacioneses(Set adjudicacioneses) {
        this.adjudicacioneses = adjudicacioneses;
    }
    public Set getListaEsperas() {
        return this.listaEsperas;
    }
    
    public void setListaEsperas(Set listaEsperas) {
        this.listaEsperas = listaEsperas;
    }




}


